name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # 00:00 on Saturdays
    - cron:  '0 0 * * SAT'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Test on Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test
      - run: npx snyk test

      - name: Upload test coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
